version: '3.6'
services:
  chrome:
    container_name: ddev-${DDEV_SITENAME}-chromedriver
    image: selenium/standalone-chrome:3.141
    restart: "no"
    volumes:
      - /dev/shm:/dev/shm
    external_links:
      - ddev-router:$DDEV_HOSTNAME
    ports:
      - 4444
      - "19647:5900"
